### ISSUE TITLE
request: don't automatically publish releases

### ISSUE THREAD

**Issue by baodrate** [dbrockman/obsidian-change-case#258]
This plugin has *very* frequent releases, corresponding to updates in any of the dependencies, but the majority do not impact the generated code. For ex (unless I'm mistaken) every tagged release >=2.0.0 generates the exact same `main.js`

The result is this plugin is always asking for an update in [plugin update tracker](https://github.com/swar8080/obsidian-plugin-update-tracker). And because I like to track my vault with git, it produces a lot of noisy commits

This might a petty, but would it be possible to slow down the release cadence? Or perhaps check if the build changes before publishing a release?

**Comment by dbrockman** [comment]
Yeah I noticed that 😄 sorry!
I've been meaning to fix it but haven't had the time.
I wanted to configure semantic release to only publish if the build output was different from the current version.
Maybe I'll just start by changing so that automatic dependency updates don't trigger a publish.

**Comment by dbrockman** [comment]
This commit should make it so that it doesn't publish new versions all the time 0e91ba0ac7add0d76c987d673b2daf0d3dc74ea1

**Comment by baodrate** [comment]
Unfortunately, it looks like it is still publishing new releases for each dependency update. Since https://github.com/dbrockman/obsidian-change-case/commit/0e91ba0ac7add0d76c987d673b2daf0d3dc74ea1:

- [2.0.135](https://github.com/dbrockman/obsidian-change-case/releases/tag/2.0.135)
- [2.0.136](https://github.com/dbrockman/obsidian-change-case/releases/tag/2.0.136)

**Comment by dbrockman** [comment]
Ok, here's the actual fix for real this time. #280
